### ISSUE TITLE
Implement ability to turn auto module off/on.

### ISSUE THREAD

**Issue by SGunner2014** [elephantLocator/UltraBot#13]
Could include a defined list of modules to ignore loading.

**Comment by elephantLocator** [comment]
#14 integration maybe?

**Comment by SGunner2014** [comment]
What do you mean "define auto things in config file"?

**Comment by elephantLocator** [comment]
Allow defining of word to look for and what to output. Will probably be best for automatic response things, like the spelling and grammar. Makes it easier for users who don't know python to change this stuff.
