### ISSUE TITLE
improve !debug version command

### ISSUE THREAD

**Issue by SGunner2014** [elephantLocator/UltraBot#16]

**Comment by SGunner2014** [comment]
Not good enough. Should have a different way of issuing the version.

**Comment by elephantLocator** [comment]
okay, how would you suggest doing it? Pulling the version from github wouldn't be a good idea as people may be running an outdated version.

Is there some way we can package in a version number with every commit at reasonably low efforts?

**Comment by SGunner2014** [comment]
Improved in 13d9edf
